version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    environment:
      # Змінна для підключення SQLAlchemy
      DATABASE_URL: postgresql://postgres:password@db:5432/chatdb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    # опціонально: можна пробросити локальні зміни коду для dev
    volumes:
      - ./src:/app/src:ro

volumes:
  postgres_data:
